package words

var Adjectives = map[string]string{
	"whole":     "Bütün",
	"about":     "Haqqında",
	"then":      "Onda",
	"wild":      "Vəhşi",
	"calm":      "Sakit",
	"early":     "Tez",
	"late":      "Gec",
	"cold":      "Soyuq",
	"hot":       "Isti",
	"free":      "Pulsuz",
	"proud":     "Qürurlu",
	"old":       "Köhnə",
	"Beautiful": "Gözəl",
	"Good":      "Yaxşı",
	"Bad":       "Pis",
	"New":       "Yeni",
	"Black":     "Qara",
	"White":     "Ağ",
	"Big":       "Böyük",
	"Cheap":     "Ucuz",
	"Expensive": "Bahalı",
	"Near":      "Yaxın",
	"Far":       "Uzak",
	"Red":       "Qırmızı",
	"Blue":      "Mavi",
	"Dark":      "Qaranlıq",
	"Light":     "Yüngül",
	"Close":     "Yaxın",
	"Distant":   "Uzaq",
	"Unusual":   "Qeyri-adi",
	"really":    "doğurdan",
}
