package words

var Nouns = map[string]string{
	"Dog":           "It",
	"window":        "pəncərə",
	"relationship":  "əlaqə",
	"key":           "achar",
	"mirror":        "güzgü",
	"pillow":        "yastiq",
	"tax":           "vergi",
	"salary":        "maaş",
	"gouverment":    "hökumət",
	"go straight":   "düz gedin",
	"room":          "otaq",
	"human":         "insan",
	"spirit":        "ruh",
	"maybe":         "ola bilər",
	"notebook":      "dəftər",
	"movie":         "kino",
	"pacific ocean": "sakit okean",
	"Day":           "Gün",
	"Book":          "Kitab",
	"Table":         "Masa",
	"Door":          "Qapı",
	"Plane":         "Təyyarə",
	"Bread":         "Qurşu",
	"Pen":           "Qələm",
	"Child":         "Uşaq",
	"Garden":        "Bağ",
	"City":          "Şəhər",
	"Fruit":         "Meyvə",
	"Valley":        "Dərə",
	"Road":          "Yol",
}
