package words

var Verbs = map[string]string{
	"To close":      "Bağlamaq",
	"To understand": "Başa duşmək",
	"To start":      "Başlamaq",
	"To write":      "Yazmaq",
	"To look":       "Baxmaq",
	"To take":       "Göturmaq",
	"To know":       "Bilmək",
	"To go":         "Getmək",
	"To come":       "Gəlmək",
	"To work":       "Işlemək",
	"To travel":     "Səyahət etmək",
	"To learn":      "Öyrənmək",
	"To read":       "Oxumaq",
	"To eat":        "Yemək",
	"To drink":      "Içmək",
	"To open":       "Açmaq",
	"To give":       "Vermək",
	"To see":        "Görmək",
	"To play":       "Oynamaq",
	"To wake up":    "Oyanmaq",
	"To rest":       "Dincəlmek",
	"To buy":        "Almaq",
	"To wash":       "Yumaq",
	"To be":         "Olmaq",
	"To cry":        "Ağlamaq",
	"To forget":     "Unutmaq",
	"To walk":       "Gəzmək",
	"To do":         "Etmək",
	"To end":        "Qurtarmaq",
	"To listen":     "Qulaq asmaq",
	"To think":      "Fikirleşmək",
	"To bring":      "Gətirmək",
	"To ask":        "Soruşmaq",
	"To call":       "Zəng vurmaq",
	"To wait":       "Gözləmək",
	"To wish":       "Arzulamaq",
	"To hope":       "Ümid etmək",
	"To send":       "Göndərmək",
	"To meet":       "Tanış olmaq",
	"To meet up":    "Görüşmək",
	"To remeber":    "Xatırlamaq",
	"To joke":       "Zarafat etmək",
	"To smell":      "Iyləmək",
	"To hear":       "Eşitmək",
	"feel":          "Hiss etmək",
}
